name: Automate Dependency Updates
run-name: Checking for outdated dependencies
on: 
  pull_request:
    branches:
      - main

jobs:
  check-if-needs-maintenance:
    name: Check if the project needs maintenance before updating dependencies
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install

      - name: Check if the project needs maintenance
        run: |
          if ! yarn run storybook; then
            echo "Project needs maintenance. Storybook failed to run."
            exit 1
          fi

  merge-dependabot-pr:
    name: Merge Pull Requests
    runs-on: ubuntu-latest
    needs: check-if-needs-maintenance
    if: success()  # This ensures it only runs if the previous job succeeds
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge updates to develop
        run: |
            curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/merges \
            -d '{"base":"main","head":"feature-branch","commit_message":"feat: upgrading deps"}'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
